# Generated by Django 5.0.4 on 2025-11-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='tickets/', verbose_name='Archivo Adjunto'),
        ),
    ]
