# Generated by Django 5.0.4 on 2025-11-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='calificacion',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='comentario_calificacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
